services:
  database:
    image: postgres:16-alpine
    container_name: agro_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: agro_user
      POSTGRES_PASSWORD: agro_password
      POSTGRES_DB: agro_db
    env_file:
      - ./apps/backend/.env
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: agro_backend
    depends_on:
      - database
    env_file:
      - ./apps/backend/.env
    environment:
      NODE_ENV: development
      RUN_SEED: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    container_name: agro_frontend
    depends_on:
      - backend
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
    command: sh -c "pnpm install --store-dir=/tmp/.pnpm-store && pnpm dev"
