services:
  database:
    image: postgres:16-alpine
    container_name: agro_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: agro_user
      POSTGRES_PASSWORD: agro_password
      POSTGRES_DB: agro_db
    env_file:
      - ./apps/backend/.env 
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: agro_backend
    depends_on:
      - database
    env_file:
      - ./apps/backend/.env 
    environment:
      NODE_ENV: development
      RUN_SEED: "false"
    ports: 
      - "3000:3000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules