FROM node:20-alpine

RUN apk add --no-cache openssl bash

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install
  
EXPOSE 3001

CMD ["pnpm", "dev"]
